### ISSUE TITLE
Missing S5P PAL NO2 product

### ISSUE THREAD

**Issue by zxdawn** [stcorp/codadef-s5p-pal#1]
Hi, thanks for adding the PAL product. I can't find the NO2 codadef, did you miss it?

**Comment by svniemeijer** [comment]
Could you explain why you would need that?
Note that CODA can read any netCDF4 file without a codadef, so you shouldn't need it.

This codadef is mainly used for verifying the file format of PAL generated products that S&T is using within the PAL system.

This codadef is also used for the detection expressions (to determine the product type of a file) which is going to be used by HARP. A [codadef with just the detection expressions for the official S5P products](https://github.com/stcorp/harp/tree/master/definitions/Sentinel5P) is already embedded in the HARP repository itself.

**Comment by zxdawn** [comment]
Ha, sorry. I got it wrong. Last month my friend told me she couldn't use harp for the PAL SO2 product. I thought it was the PAL NO2 product.
